Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [libyuv/try/ios_arm64_rel](https://cr-buildbucket.appspot.com/build/8701068423610111073) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/7018293?checksPatchset=3&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[295/1898] ACTION //buildtools/third_party/libc++:copy_sysroot_modulemaps(//build/toolchain/mac:clang_x64)
python3 ../../build/noop.py
missing local outputs out/Release-iphoneos/sdk/xcode_links/MacOSX12.1.sdk/usr/include/DarwinBasic.modulemap: lstat /Volumes/Work/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/DarwinBasic.modulemap: no such file or directory
error: 1 steps failed: missing local outputs out/Release-iphoneos/sdk/xcode_links/MacOSX12.1.sdk/usr/include/DarwinBasic.modulemap: lstat /Volumes/Work/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/DarwinBasic.modulemap: no such file or directory
```
#### [Click here for more information](https://logs.chromium.org/logs/libyuv/buildbucket/cr-buildbucket/8701068423610111073/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1760410694
Attention: {"person_ident":"Gerrit User 1339017 \u003c1339017@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}